# Conclusion

## Takeaways

In this project we explored a breadth of analysis categories in the intricate 
game of chess. As such, our takeaways are similarly broad yet limited in scope.
There were no groundbreaking discoveries here, which isn't surprising, but we
did gain an understanding of how to manipulate a curated, extensive, and
complicated dataset, along with uncovering some curiosities that could quite 
possibly inspire future work.

It's well known just how frequently draws occur in high-level chess. And yet,
seeing a visual breakdown of that very frequency is striking. Likewise, the
ratings graphics helped solidify our grasp on how modern chess is organized and
recorded--ratings are not static nor smooth, and sometimes individual players
have multiple ratings for the very same game depending on the setting (online v
offline).

Furthermore, even considering how long chess in its modern form has been
developed, there isn't a consensus on the precisely best moves at the top level.
That's a good thing--flexibility at a top level indicates a game in good health,
and chess has plenty of room to flourish in the coming decades. Although a move
does not necessarily seal the result of a game, it can determine the immediately
following sequence, and moreover dictate the type of game the players have
before them.

## Limitations

While chess's history is thoroughly documented, and thankfully [chess.com](chess.com)
and modern chess as a whole has a consistent notational move system, it took a
fairly long time to work the dataset into an feasible one. We had to automate 
the collection of many, many individual game files, then build a parser from 
scratch to interpret the `.pgn` files, which cut away a lot of potential hours
from developing our analysis further.

Regarding the actual data, it was troublesome coming up with schematics to
reasonably display what were essentially high dimensional categorical variables.
Often, we had to make an arbitrary cutoff or subsection on the moves or players,
limiting the robustness of our wide approach. Furthermore, player names weren't
normalized across events, which prevented us from running much of an analysis
on the black players or games were our players were black (some appear as the
black pieces many times). We would have liked to use the date feature as well,
but that was unfortunately dirty beyond the point of usability.

## Future Work

Our findings do present a wide array of possible jumping off points. Result 
rates could be controlled for games versus other world champions or 
grandmasters, granting a fairer margin, and then analyzing the winningest and
losingest initial moves from there. Alternatively, with an algorithm to filter
moves into different phases of the games, one could also categorize the use
each assortment of piece sees in that phase, and how strongly that indicates the
eventual result. There are, of course, AI that trump even the best of players,
as well as advanced algorithms that estimate each players current chances of
winning, so we would not aspire to build a model to replace either of those.
Merely to develop an analysis that grants fledgling players a new angle to
improve their strategies within the game of chess.


