--- 
title: "Chess Grandmasters over Time"
author: "Andre Evard, Braden Huffman"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

This project centers on the highly organized game of chess, and in particular,
the highest level of play. Chess is one of the longest standing popular
competitive games, and was a pioneer for in data regulation, bookkeeping, and 
rating systems. Nowadays, even with the astounding rise of video games, chess
remains popular amongst a variety of age groups and on broadcasting websites
such as [Twitch.tv](https://www.twitch.tv/directory/game/Chess). It also has
a variety of digital platforms, such as [chess.com](https://www.chess.com/),
which often function as services to play the game and host records both.

Since both of us are competitive game players, and we have an interest in chess,
we were particularly interested in the strategic complexity of this game--especially
with its monumental history. In particular, it spawned the [ELO Rating system](https://en.wikipedia.org/wiki/Elo_rating_system), 
which has inspired the vast majority of tournament player ranking 
systems. In this system, every player has a score, and whenever two players
play against one another, their scores are adjusted accordingly. If the player
with a much higher rating won, then the ratings are judged to be fairly accurate
and do not shift much. If the lower rated player won, however, or if they tied,
then both players are shifted toward the middle. This system was created in the 
mid 20th century and proved highly successful, so we are interested
in studying how the pinnacle of players perform under it. Of course, organized
chess predated it, so we will still be observing some players who played before
the full introduction of the system.

Furthermore, since organized chess has carefully recorded their
tournament results since the mid 1800s, and the title "World Champion" has
been passed through sixteen players since then, we were interested in examining
how players over time have approached the game. Therefore, since analysis beyond
the initial moves becomes too cluttered to discern much information, we chose
to examine the very first moves of the game, where it is at its most regular.
In terms of the game's strategy, we were particularly interested in seeing in 
how frequently the exact same openers are chosen, and if and when they were, 
how they shifted the probable outcomes of the game.

